In [ ]:
import pandas as pd
import io
import requests
import zipfile
from sklearn.cluster import DBSCAN
import numpy as np


# Load directly from GitHub
url = "https://github.com/clarabot1/LA28_bus_network/raw/main/airbnb_listings.csv.zip"  # Updated URL

# Download the zip file
response = requests.get(url)
response.raise_for_status()  # Check for download errors

# Extract the CSV file from the zip file
with zipfile.ZipFile(io.BytesIO(response.content)) as zip_ref:
    with zip_ref.open("airbnb_listings.csv") as csv_file:
        df = pd.read_csv(csv_file)

# Show the dataframe
df.head()
airbnb_listings = df

# Data Import

In [ ]:
airbnb_listings.head(1)

In [ ]:
# keep colums that are id, accommodates, latitude, longitude
airbnb_listings = airbnb_listings[["id", "accommodates", "latitude", "longitude"]]
# remove duplicates
airbnb_listings = airbnb_listings.drop_duplicates()
# remove rows with null values
airbnb_listings = airbnb_listings.dropna()
# remove rows with 0 values
airbnb_listings = airbnb_listings[airbnb_listings["accommodates"] > 0]
airbnb_listings.head(5)

In [ ]:
# Load directly from GitHub
url = "https://raw.githubusercontent.com/gr-oll/SLO_LA_Olympics/refs/heads/main/hotels.csv"
df = pd.read_csv(url)

# Show the dataframe
df.head()

hotels = df

In [ ]:
# keep only the relevant columns
hotels = hotels[["id", "people", "lon", "lat"]]
# already handled duplicates and null values
hotels.head(5)

In [ ]:
#accommodates summary statistics
display(airbnb_listings["accommodates"].describe())
#people summary statistics
hotels["people"].describe()

In [ ]:
# Align column names for merging
hotels_renamed = hotels.rename(columns={"lat": "latitude", "lon": "longitude", "people": "accommodates"})

hotels_renamed["id"] = "H" + hotels_renamed["id"].astype(str)
airbnb_listings["id"] = "A" + airbnb_listings["id"].astype(str)

# Merge the dataframes vertically
merged_df = pd.concat([airbnb_listings, hotels_renamed], ignore_index=True)

# Display the merged dataframe
merged_df.head()

In [ ]:
#count the number of listings
len(merged_df)

In [ ]:
#sum of accommodates
merged_df["accommodates"].sum()

# Create clusters

## OG Clusters

In [ ]:
from sklearn.cluster import KMeans
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Define the number of clusters (you can adjust this based on your requirements)
num_clusters = 35

# Prepare the data for clustering (latitude, longitude, accommodates)
features_for_clustering = merged_df[["latitude", "longitude", "accommodates"]].copy()

# Normalize the accommodates column to balance its scale with latitude and longitude
scaler = MinMaxScaler()
features_for_clustering["accommodates"] = scaler.fit_transform(features_for_clustering[["accommodates"]])

# Perform KMeans clustering
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
merged_df["kmeans_cluster"] = kmeans.fit_predict(features_for_clustering)

# Analyze the clusters
cluster_summary = merged_df.groupby("kmeans_cluster").agg(
    total_accommodates=("accommodates", "sum"),
    count=("id", "count"),
    avg_latitude=("latitude", "mean"),
    avg_longitude=("longitude", "mean")
)

# Display the cluster summary
cluster_summary

In [ ]:
merged_df

In [ ]:
# Define a color palette for the clusters
import matplotlib.cm as cm
import matplotlib.colors as colors
import folium

# Generate a color map with distinct colors for each cluster
num_clusters = merged_df["kmeans_cluster"].nunique()
colormap = cm.get_cmap("tab20", num_clusters)
cluster_colors = [colors.rgb2hex(colormap(i)[:3]) for i in range(num_clusters)]

# Create a folium map centered around Los Angeles
m = folium.Map(location=[34.0522, -118.2437], zoom_start=12)

# Map cluster IDs to integer indices
cluster_id_to_index = {cluster_id: idx for idx, cluster_id in enumerate(merged_df["kmeans_cluster"].unique())}

# Add points to the map with colors based on their cluster
for _, row in merged_df.iterrows():
    cluster_index = cluster_id_to_index[row["kmeans_cluster"]]
    cluster_color = cluster_colors[cluster_index]
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=5,
        color=cluster_color,
        fill=True,
        fill_color=cluster_color,
        fill_opacity=0.7,
        popup=f"ID: {row['id']}, Accommodates: {row['accommodates']}, Cluster: {row['kmeans_cluster']}"
    ).add_to(m)


# Display the map
m

## Break Down the Big Ones

In [ ]:
def subcluster_large_cluster(cluster_id, n_subclusters, df):
    cluster_df = df[df["kmeans_cluster"] == cluster_id]
    kmeans_sub = KMeans(n_clusters=n_subclusters, random_state=0, n_init=10)
    cluster_df["sub_cluster"] = kmeans_sub.fit_predict(cluster_df[["latitude", "longitude"]])
    df.loc[df["kmeans_cluster"] == cluster_id, "sub_cluster"] = (
        str(cluster_id) + "_" + cluster_df["sub_cluster"].astype(str)
    )
    return df

# Subcluster specified clusters
for cluster_id, n_subclusters in [(0, 4), (9, 6), (17, 3), (21, 4), (25, 4), (29, 2)]:
    if cluster_id in merged_df["kmeans_cluster"].unique():
        merged_df = subcluster_large_cluster(cluster_id, n_subclusters, merged_df)
    else:
        print(f"Cluster {cluster_id} not found.")


merged_df["sub_cluster"] = merged_df["sub_cluster"].fillna(merged_df["kmeans_cluster"].astype(str))
# Print the first few rows to verify
print(merged_df.head())

In [ ]:
merged_df

In [ ]:
#drop cluster 10 - avalon 
merged_df = merged_df[merged_df["kmeans_cluster"] != 10]

In [ ]:
# Analyze the clusters
cluster_summary = merged_df.groupby("sub_cluster").agg(
    total_accommodates=("accommodates", "sum"),
    count=("id", "count"),
    avg_latitude=("latitude", "mean"),
    avg_longitude=("longitude", "mean")
)

# Display the cluster summary
cluster_summary.describe()

In [ ]:
import matplotlib.cm as cm
import matplotlib.colors as colors
import folium

# Use a continuous colormap like 'rainbow' to ensure each cluster has a unique color
num_clusters = merged_df["sub_cluster"].nunique()
colormap = cm.get_cmap("rainbow", num_clusters)
cluster_colors = [colors.rgb2hex(colormap(i)[:3]) for i in range(num_clusters)]

m = folium.Map(location=[34.0522, -118.2437], zoom_start=12)
cluster_id_to_index = {cluster_id: idx for idx, cluster_id in enumerate(merged_df["sub_cluster"].unique())}

for _, row in merged_df.iterrows():
    cluster_index = cluster_id_to_index[row["sub_cluster"]]
    cluster_color = cluster_colors[cluster_index]
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=5,
        color=cluster_color,
        fill=True,
        fill_color=cluster_color,
        fill_opacity=0.7,
        popup=f"ID: {row['id']}, Accommodates: {row['accommodates']}, Cluster: {row['sub_cluster']}"
    ).add_to(m)
for cluster_id, row in cluster_summary.iterrows():
    folium.Marker(
        location=[row['avg_latitude'], row['avg_longitude']],
        popup=f"Cluster: {cluster_id}<br>Total Accommodates: {row['total_accommodates']}<br>Count: {row['count']}",
        icon=folium.Icon(color="blue")
    ).add_to(m)
m

# Accomodations Clusters

In [ ]:
# Create a map centered around Los Angeles
map_center = [34.0522, -118.2437]
cluster_map = folium.Map(location=map_center, zoom_start=10)

# Add markers for each cluster
for cluster_id, row in cluster_summary.iterrows():
    folium.Marker(
        location=[row['avg_latitude'], row['avg_longitude']],
        popup=f"Cluster: {cluster_id}<br>Total Accommodates: {row['total_accommodates']}<br>Count: {row['count']}",
        icon=folium.Icon(color="blue")
    ).add_to(cluster_map)

# Display the map
cluster_map

# Bus Divisions

In [ ]:
#Depot

####Depot dataframe and map

import pandas as pd

# Load directly from GitHub
url = "https://raw.githubusercontent.com/clarabot1/LA28_bus_network/refs/heads/main/bus_divisions_cleaned-2.csv"
df = pd.read_csv(url)

# Show the dataframe
df.head()

bus_divisions = df

# prompt: print the different values in FACILITY column, and drop all lines that are either TERMINAL and LOCATIONS

print(df['FACILITY'].unique())


bus_divisions = bus_divisions[~bus_divisions['FACILITY'].str.contains('LOCATION', na=False)]
bus_divisions = bus_divisions[~bus_divisions['FACILITY'].str.contains('TERMINAL', na=False)]


bus_divisions

In [ ]:

# prompt: #drop rows with NaN in address column in the bus_divisions dataframe, as well as rows with the following 4Digits: 4,6,10,11,20,21,22

# Drop rows with NaN in 'address' column
bus_divisions.dropna(subset=['Address'], inplace=True)

# Define the 4Digits to exclude
four_digits_to_exclude = [4, 6, 10, 11, 12, 20, 21, 22]

# Convert '4Digits' column to numeric, coercing errors to NaN
bus_divisions['4Digits'] = pd.to_numeric(bus_divisions['4Digits'], errors='coerce')

# Drop rows where '4Digits' is in the list of values to exclude
bus_divisions = bus_divisions[~bus_divisions['4Digits'].isin(four_digits_to_exclude)]

#Now you can work with the modified 'bus_divisions' DataFrame
bus_divisions



print(bus_divisions[bus_divisions.isna().any(axis=1)])



# Create a map centered around Los Angeles
map_center = [34.0522, -118.2437]
bus_division_map = folium.Map(location=map_center, zoom_start=10)

# Add markers for each bus division location
for index, row in bus_divisions.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=f"Bus Division: {row['NAME']}",  # Assuming 'division_name' column exists
        icon=folium.Icon(color="green")
    ).add_to(bus_division_map)

bus_division_map

#### Divisions capacity

In [ ]:


import pandas as pd

# Load directly from GitHub
url = "https://raw.githubusercontent.com/clarabot1/LA28_bus_network/refs/heads/main/bus_divisions_cleaned_capacity.csv"
df = pd.read_csv(url)

# Show the dataframe
df.head()

depot_capacity = df
depot_capacity = depot_capacity.rename(columns={'Amonut': 'amount'})

In [ ]:


# prompt: compute total capacity of each depot, and add the corresponding latitude and longitude from bus_divisions based on the matching 4Digits column

# Merge depot capacity with bus division data based on the '4Digits' column
merged_depot_data = pd.merge(depot_capacity, bus_divisions, on='4Digits', how='left')

# Calculate the total capacity for each depot
merged_depot_data['Total Capacity'] = merged_depot_data.groupby('4Digits')['amount'].transform('sum')

# Select relevant columns and display the result
# The 'Latitude' and 'Longitude' columns were likely renamed during the merge,
# so we need to use their new names.
depot_capacity_with_coordinates = merged_depot_data[['4Digits', 'Total Capacity', 'Latitude_y', 'Longitude_y']].drop_duplicates()
depot_capacity_with_coordinates = depot_capacity_with_coordinates.rename(columns={'Latitude_y': 'Latitude', 'Longitude_y': 'Longitude'})
depot_capacity_with_coordinates

In [ ]:
# sum total capacity
total_capacity = depot_capacity_with_coordinates['Total Capacity'].sum()
total_capacity

# Olympic venues

In [ ]:

####Dataframe and map

import pandas as pd

# Load directly from GitHub
url = "https://raw.githubusercontent.com/clarabot1/LA28_bus_network/refs/heads/main/Venue_data-4.csv"
df = pd.read_csv(url)

# Show the dataframe
df.head()

venues_locations = df

venues_locations

In [ ]:

map_center = [34.0522, -118.2437]
la_map_venues = folium.Map(location=map_center, zoom_start=10)

# Add markers for each venue location
for index, row in venues_locations.iterrows():
    try:
        latitude = float(row['Latitude'])
        longitude = float(row['Longitude'])
        folium.Marker(
            location=[latitude, longitude],
            popup=row['Venue'],  # Assuming 'Venue' column exists
            icon=folium.Icon(color="purple")
        ).add_to(la_map_venues)
    except (ValueError, TypeError):
        print(f"Skipping row {index} due to invalid latitude/longitude values.")
    except KeyError:
      print(f"Skipping row {index} due to missing 'Venue' column")

la_map_venues

In [ ]:

####Capacity

# prompt: create a copy of venues_locations called venues locations capacity, and only return venue, latitude, longitude and capacity

venues_locations_capacity = venues_locations[['Venue', 'Latitude', 'Longitude', 'Approx. Capacity']].copy()
venues_locations_capacity

# Distance Matrix

In [ ]:
#reset the index of the cluster summary dataframe
cluster_summary = cluster_summary.reset_index()
#drop the sub_cluster column
cluster_summary = cluster_summary.drop(columns=['sub_cluster'])
cluster_summary

In [ ]:
# add a column to the venues_locations_capacity with an id Starting with V
venues_locations_capacity['id'] = 'V' + (venues_locations_capacity.index + 1).astype(str)
# add a column to the cluster summary with an id Starting with C
cluster_summary['id'] = 'A' + (cluster_summary.index + 1).astype(str)
display(venues_locations_capacity.head(5))
cluster_summary.head(5)

In [ ]:
#in venues_locations_capacity, rename avg with latitude and longitude
venues_locations_capacity = venues_locations_capacity.rename(columns={'avg_latitude': 'Latitude', 'avg_longitude': 'Longitude'})
venues_locations_capacity

In [ ]:
# Select relevant columns from both dataframes
venues_data = venues_locations_capacity[['Latitude', 'Longitude', 'id']]
clusters_data = cluster_summary[['avg_latitude', 'avg_longitude', 'id']].rename(
    columns={'avg_latitude': 'Latitude', 'avg_longitude': 'Longitude'}
)

# Concatenate the dataframes vertically
df_matrix = pd.concat([venues_data, clusters_data], ignore_index=True)

# Display the merged dataframe
df_matrix.head()

In [ ]:
import googlemaps

# Replace "YOUR_API_KEY" with your actual Google Maps API key
gmaps = googlemaps.Client(key="API_KEY")

# Function to calculate distance matrix
def calculate_distance_matrix(origins, destinations):
    distance_matrix = gmaps.distance_matrix(origins, destinations, mode="driving")
    return distance_matrix

# Example usage
origins = df_matrix['id'].tolist()
destinations = df_matrix['id'].tolist()


# Assuming df_matrix DataFrame has columns 'Latitude' and 'Longitude'
origin_coords = df_matrix[['Latitude', 'Longitude']].values.tolist()
dest_coords = df_matrix[['Latitude', 'Longitude']].values.tolist()

distance_matrix_data = []
for i in range(len(origins)):
  try:
    distance_matrix_row = []
    for j in range(len(destinations)):
        # Access the origin and destination coordinates as tuples
        origin_coord = tuple(origin_coords[i])  # Convert to tuple
        dest_coord = tuple(dest_coords[j])  # Convert to tuple

        distance_result = gmaps.distance_matrix(origin_coord, dest_coord, mode="driving")
        if distance_result['rows'][0]['elements'][0]['status'] != 'OK':
          distance_matrix_row.append(np.nan)
        else:
          distance_matrix_row.append(distance_result['rows'][0]['elements'][0]['distance']['value'])
    distance_matrix_data.append(distance_matrix_row)
  except Exception as e:
    print(f"Error calculating distance for row {i}: {e}")
    distance_matrix_data.append([np.nan] * len(destinations))


distance_matrix_df = pd.DataFrame(distance_matrix_data, index = origins, columns = destinations)
##distances in meters

In [ ]:
# Assuming df_matrix DataFrame has columns 'Latitude' and 'Longitude'
origin_coords = df_matrix[['Latitude', 'Longitude']].values.tolist()
dest_coords = df_matrix[['Latitude', 'Longitude']].values.tolist()
origins = df_matrix['id'].tolist()
destinations = df_matrix['id'].tolist()

time_matrix_data = []
for i in range(len(origins)):
  try:
    time_matrix_row = []
    for j in range(len(destinations)):
        origin_coord = tuple(origin_coords[i])  # Convert to tuple
        dest_coord = tuple(dest_coords[j])  # Convert to tuple

        distance_result = gmaps.distance_matrix(origin_coord, dest_coord, mode="driving")
        if distance_result['rows'][0]['elements'][0]['status'] != 'OK':
          time_matrix_row.append(np.nan)
        else:
          time_matrix_row.append(distance_result['rows'][0]['elements'][0]['duration']['value'])
    time_matrix_data.append(time_matrix_row)
  except Exception as e:
    print(f"Error calculating time for row {i}: {e}")
    time_matrix_data.append([np.nan] * len(destinations))

time_matrix_df = pd.DataFrame(time_matrix_data, index = origins, columns = destinations)
# times in seconds

time_matrix_df

In [ ]:
#export the distance matrix to a csv file
distance_matrix_df.to_csv("distance_matrix.csv")
#export the time matrix to a csv file
time_matrix_df.to_csv("time_matrix.csv")

In [ ]:
#export venues_locations_capacity to a csv file
venues_locations_capacity.to_csv("venues.csv", index=False)
#export cluster_summary to a csv file
cluster_summary.to_csv("clusters_central_location.csv", index=False)
#export merged_df to a csv file
merged_df.to_csv("accomodations.csv", index=False)

In [ ]:
import googlemaps
from datetime import datetime

# Initialize the Google Maps client with your API key
gmaps = googlemaps.Client(key='KEY')

# Build list of origin and destination tuples using the dataframe coordinates
origins = accomodations_clusters[['avg_latitude', 'avg_longitude']].apply(lambda row: (row['avg_latitude'], row['avg_longitude']), axis=1).tolist()
destinations = bus_terminals[['Latitude', 'Longitude']].apply(lambda row: (row['Latitude'], row['Longitude']), axis=1).tolist()

# Request the distance matrix in batches to avoid MAX_DIMENSIONS_EXCEEDED error
max_elements = 100
max_destinations_per_request = 25  # Free API limit for destinations per request
destination_batch_size = max_destinations_per_request
origin_batch_size = max_elements // destination_batch_size

# Initialize an empty results matrix
results = [[None] * len(destinations) for _ in range(len(origins))]

for i in range(0, len(origins), origin_batch_size):
    origin_chunk = origins[i:i+origin_batch_size]
    for j in range(0, len(destinations), destination_batch_size):
        destination_chunk = destinations[j:j+destination_batch_size]
        response = gmaps.distance_matrix(origin_chunk, destination_chunk, mode='driving')
        for index_in_chunk, row in enumerate(response['rows']):
            result_row = i + index_in_chunk
            for dest_index, element in enumerate(row['elements']):
                if element['status'] == 'OK':
                    results[result_row][j+dest_index] = element['duration']['value']
                else:
                    results[result_row][j+dest_index] = None

time_matrix = pd.DataFrame(results, index=accomodations_clusters['id'], columns=bus_terminals['id'])
time_matrix

id,BT25,BT07,BT13,BT10,BD01,BD02,BD05,BD06,BD09,BD11,...,BL22,BL23,BT26,BL19,BT04,BT19,BL03,BL07,BT05,BT15
id,,,,,,,,,,,,,,,,,,,,,
A1,2234,1766,1370,2384,2077,1938,1932,2472,1853,2021,...,2529,2558,1594,1861,1854,1850,2308,1811,1372,2128
A2,1750,1294,1042,1912,1632,1787,2402,1988,1382,1930,...,2580,2314,1486,1685,1472,1664,1818,1758,954,1717
A3,1254,779,948,1397,1116,1271,2086,1594,866,1415,...,2265,1798,1356,1170,957,1149,1302,1243,341,1201
A4,1741,1267,650,1885,1604,1726,2050,2082,1354,1809,...,2647,2346,1119,1700,1539,1638,1790,1599,814,1689
A5,2270,1640,2254,2414,1681,1453,2260,2348,1561,1614,...,2979,610,2077,1731,1724,1255,1826,1442,2052,1394
A6,2628,1979,2593,2693,2022,1839,2873,2634,1900,2000,...,3592,1144,2463,2116,2110,1641,2178,1828,2391,1780
A7,1489,1069,1479,1632,1161,786,1466,1764,1042,716,...,2166,1518,1260,949,943,830,1306,773,1343,1135
A8,1230,1933,2268,1603,2163,2282,2980,1108,1913,2350,...,3159,2813,2353,1974,1966,2194,2232,2140,1774,2229
A9,3111,2902,2604,3466,2995,2619,1744,3349,2875,2658,...,2059,3352,2615,2783,2776,2663,3140,2606,2648,2969
A10,2575,1793,2407,2642,1836,1802,3110,2559,1714,2038,...,3810,1535,2406,2092,2021,1696,1992,1866,2205,1559
A11,3788,3712,3314,4276,3809,3433,3142,4026,3689,3472,...,2522,4166,3326,3593,3586,3477,3954,3420,3326,3783
A12,1350,1186,1367,1724,1524,1679,2077,1588,1273,1822,...,2255,2205,1783,1577,1364,1556,1709,1650,874,1608
A13,1386,1342,1523,1760,1679,1834,2232,1624,1429,1977,...,2411,2361,1938,1732,1519,1711,1865,1805,1029,1764
A14,1332,1636,1817,1706,1974,2129,2529,1570,1723,2272,...,2708,2655,2233,2076,1814,2006,2159,2100,1324,2058
A15,250,1075,1543,673,1306,1425,2556,582,1056,1493,...,2944,1865,1496,1116,1109,1337,1374,1283,1341,1281
A16,1918,1752,1354,2315,1849,1473,1250,2155,1729,1511,...,1612,2205,1365,1633,1626,1517,1993,1460,1455,1822
A17,1442,2103,2570,1774,2224,2190,3494,1149,2102,2421,...,3823,2451,2523,2144,2136,2062,2058,2249,2368,1866
A18,1234,1895,2362,1566,2126,2245,3376,987,1876,2312,...,3626,2660,2315,1936,1928,2156,2194,2103,2160,2075
A19,1992,1571,1173,2135,1668,1529,1400,2267,1633,1611,...,1996,2149,1185,1452,1445,1441,1899,1402,1741,1719
A20,1496,1076,534,1640,1173,1034,1257,1772,1138,1116,...,1853,1654,689,957,950,945,1404,907,1319,1224
A21,1953,1533,793,2097,1630,1491,1543,2229,1595,1573,...,2140,2111,1146,1414,1407,1402,1861,1364,1131,1681
A22,1521,1101,703,1664,1198,1058,1162,1796,1163,1141,...,1758,1679,714,981,975,970,1428,932,1442,1248
A23,1460,830,1443,1603,870,643,1876,1583,751,804,...,2576,564,1266,920,913,444,1015,632,1241,584
A24,3124,2915,2617,3479,3008,2632,1757,3361,2888,2671,...,1997,3365,2628,2796,2789,2676,3153,2619,2661,2982
A25,2537,1889,2502,2603,1931,1749,2543,2543,1810,1909,...,3263,1053,2372,2026,2019,1550,2088,1738,2300,1689
A26,635,1338,1805,1008,1568,1687,2579,1011,1318,1755,...,2757,2218,1758,1379,1371,1599,1637,1545,1389,1634
A27,865,1279,1460,1316,1617,1772,2370,1103,1367,2003,...,2549,2299,1876,1627,1457,1649,1885,1793,949,1701
A28,814,1517,1719,1188,1748,1867,2430,1033,1498,1934,...,2609,2398,1937,1558,1551,1779,1816,1725,1289,1813
A29,678,1292,1640,970,1523,1642,2685,1034,1273,1709,...,2864,2262,1712,1333,1326,1554,1591,1500,1469,1608
A30,5261,5053,4755,5617,5146,4770,3894,5499,5026,4809,...,4210,4928,4766,4934,4927,4814,5291,4757,4798,5119
A31,1161,799,770,1305,1137,1415,2504,1437,886,1483,...,2580,1818,1142,1107,841,1169,1322,1274,629,1221
A32,2496,2420,2022,2984,2517,2141,1850,2734,2397,2180,...,901,2874,2034,2301,2294,2185,2662,2128,2033,2491
A33,1287,1137,1318,1661,1474,1629,1822,1525,1224,1773,...,2000,2156,1734,1528,1315,1507,1660,1601,824,1559
A34,1385,1235,1416,1759,1572,1727,1799,1623,1322,1870,...,1978,2254,1832,1625,1413,1604,1758,1699,922,1657
A35,2243,2093,1988,2617,2484,2107,1383,2481,2180,2146,...,1088,2840,2000,2267,2261,2151,2628,2094,1780,2457
A36,3682,3605,3207,4169,3703,3326,3035,3919,3582,3365,...,2434,4059,3219,3486,3480,3370,3847,3313,3219,3676
A37,1783,1363,1774,1927,1456,1080,1559,2059,1336,1076,...,2278,1204,1554,1244,1237,1124,1601,1047,1638,1430
A38,5140,4931,4633,5495,5024,4648,3773,5377,4904,4687,...,4088,5381,4644,4812,4805,4692,5169,4635,4677,4998
A39,2454,1672,2286,2521,1715,1681,2989,2438,1593,1917,...,3689,1414,2284,1971,1900,1574,1871,1745,2084,1438
A40,1134,1467,2072,1199,1510,1476,2780,1129,1388,1707,...,3433,1545,2025,1646,1638,1348,1344,1536,1870,1152
A41,840,998,1179,1214,1335,1490,1890,1078,1085,1633,...,2069,2017,1594,1388,1175,1367,1521,1461,685,1420
A42,4172,3964,3666,4528,4056,3681,2805,4410,3937,3719,...,3120,4414,3677,3845,3838,3725,4202,3668,3709,4030
A43,1392,554,1168,1403,654,563,1894,1460,475,821,...,2594,1002,1167,853,782,547,753,650,966,368
A44,1982,1562,1387,2126,1655,1279,1097,2258,1535,1318,...,1720,2012,1398,1443,1436,1323,1800,1266,1837,1629
A45,2876,2800,2402,3363,2897,2521,2229,3114,2777,2559,...,1628,3253,2413,2680,2674,2565,3041,2507,2413,2870
A46,983,634,1052,1127,455,435,1670,1259,632,606,...,2318,1056,752,386,437,347,806,383,838,625
A47,1322,901,837,1465,998,859,1550,1597,964,942,...,2181,1479,617,782,775,771,1229,732,1176,1049
A48,1394,905,278,1538,1146,1039,1685,1669,964,1122,...,2281,1659,201,810,783,951,1409,912,957,1229
A49,949,519,629,1092,791,739,1864,1224,581,807,...,2460,1360,283,435,434,651,1017,598,794,916
A50,1225,804,1032,1368,906,665,1588,1500,867,674,...,2288,1387,842,685,678,679,1137,488,1079,957
A51,949,311,907,1092,529,721,1852,1224,387,788,...,2525,1341,697,286,393,632,914,579,705,813